namespace ApexionGame.SourceGen.Tests;

/// <summary>
/// Absolute paths to the Unity assemblies the integration tests compile against.
/// The other half of this class is generated by UnityDllPaths.targets before every build.
/// </summary>
/// <remarks>
/// <see cref="All"/> is empty when Unity paths could not be resolved; callers should treat that
/// as "skip", not "fail" — see <see cref="IsResolved"/>.
/// </remarks>
internal static partial class UnityDllPaths
{
    private static readonly string[] s_all = InitAllOrEmpty();
    private static readonly string s_unityModulesPath = InitModulesPathOrEmpty();
    private static readonly string s_unityScriptAssembliesPath = InitScriptAssembliesPathOrEmpty();

    public static string[] All => s_all;

    public static string UnityModulesPath => s_unityModulesPath;

    public static string UnityScriptAssembliesPath => s_unityScriptAssembliesPath;

    /// <remarks>
    /// Checks the files are actually there, not just that the build wrote some paths. A wiped
    /// Library/ScriptAssemblies should skip the integration tier, not crash it inside Roslyn.
    /// </remarks>
    public static bool IsResolved
        => s_all.Length > 0
        && System.Array.TrueForAll(s_all, static path => System.IO.File.Exists(path));

    public const string SkipReason =
        "Unity assemblies were not found. Set UNITY_OS_INSTALL_ROOT to the Unity installation "
        + "directory and open the Unity project once so Library/ScriptAssemblies is populated.";

    static partial void InitAll(ref string[] value);

    static partial void InitUnityModulesPath(ref string value);

    static partial void InitUnityScriptAssembliesPath(ref string value);

    private static string[] InitAllOrEmpty()
    {
        var value = System.Array.Empty<string>();
        InitAll(ref value);
        return value ?? System.Array.Empty<string>();
    }

    // Called directly rather than through a delegate: a partial method with no implementing
    // declaration cannot be converted to one.
    private static string InitModulesPathOrEmpty()
    {
        var value = string.Empty;
        InitUnityModulesPath(ref value);
        return value ?? string.Empty;
    }

    private static string InitScriptAssembliesPathOrEmpty()
    {
        var value = string.Empty;
        InitUnityScriptAssembliesPath(ref value);
        return value ?? string.Empty;
    }
}
