#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatVariantTypeGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatVariantTypeGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using EncosyTower.EnumExtensions;
using Unity.Mathematics;
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;

                p.PrintLine("/// <summary>");
                p.PrintLine("/// Represents a collection of supported value types that can be used in this stat system.");
                p.PrintLine("/// </summary>");
                p.PrintLine("[EnumExtensions]");
                p.PrintLine("public enum StatVariantType : byte");
                p.OpenScope();
                {
                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine("/// <summary>");
                        p.PrintBeginLine("/// <see cref=\"").Print(record.Type).Print("\"/> | ").Print(record.Size)
                            .PrintEndLineIf(record.Size > 1, " bytes.", " byte.");
                        p.PrintLine("/// </summary>");
                        p.PrintBeginLine(record.Name).Print(" = ").Print(i).PrintEndLine(",");
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine("partial interface IStatVariantTypeExtensions { }");
                p.PrintEndLine();

                p.PrintLine("partial struct StatVariantTypeExtended { }");
                p.PrintEndLine();

                p.PrintLine("static partial class StatVariantTypeExtensions");
                p.OpenScope();
                {
                    p.PrintLine("partial class DisplayNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class FixedDisplayNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class FixedNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class Names { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class UnderlyingValues { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class Values { }");
                    p.PrintEndLine();
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.COMMON_FOLDER)
            );

            context.AddCode("StatVariantType.gen.cs", p.Result);
        }
    }
}

#endif
