#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using System.Collections.Generic;
using System.Linq;
using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatDataSizeGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatDataSizeGenerator));
            p.PrintEndLine();

            WriteReferenceBlock(ref p);

            p.PrintLine(@"#pragma warning disable
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;
                var uniqueSizes = new HashSet<int>(active.Select(static x => x.Size));
                var sizes = uniqueSizes.OrderBy(static x => x).ToArray();

                p.PrintLine("/// <summary>");
                p.PrintLine("/// Represents a collection of supported data sizes, in bytes, to store stat variants.");
                p.PrintLine("/// </summary>");
                p.PrintLine("public enum StatDataSize : byte");
                p.OpenScope();
                {
                    for (var i = 0; i < sizes.Length; i++)
                    {
                        var size = sizes[i];

                        if (size % 2 != 0)
                        {
                            continue;
                        }

                        p.PrintLine("/// <summary>");
                        p.PrintBeginLine("/// ").Print(size).PrintEndLineIf(size > 1, " bytes.", " byte.");
                        p.PrintLine("/// </summary>");
                        p.PrintBeginLine("Size").Print(size).Print(" = ").Print(size).PrintEndLine(",");
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine("partial interface IStatDataSizeExtensions { }");
                p.PrintEndLine();

                p.PrintLine("partial struct StatDataSizeExtended { }");
                p.PrintEndLine();

                p.PrintLine("static partial class StatDataSizeExtensions");
                p.OpenScope();
                {
                    p.PrintLine("partial class DisplayNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class FixedDisplayNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class FixedNames { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class Names { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class UnderlyingValues { }");
                    p.PrintEndLine();

                    p.PrintLine("partial class Values { }");
                    p.PrintEndLine();
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.COMMON_FOLDER)
            );

            context.AddCode("StatDataSize.gen.cs", p.Result);
        }

        private static void WriteReferenceBlock(ref Printer p)
        {
            var active = StatTypeTable.Active;
            var maxLength = active.Select(static x => x.Name.Length).Max();
            var pad4 = maxLength - 4;

            p.PrintBeginLine("/// ").PrintEndLine("<reference>");
            p.PrintBeginLine("/// ").PrintEndLine("LIST OF SUPPORTED TYPES AND THEIR SIZE");
            p.PrintBeginLine("/// ").Print("TYPE").Print(' ', pad4).Print(" | SIZE (bytes)").PrintEndLine();
            p.PrintBeginLine("/// ").Print('-', maxLength).Print(" | ------------").PrintEndLine();

            for (var i = 0; i < active.Length; i++)
            {
                var record = active[i];
                var pad = maxLength - record.Name.Length;

                p.PrintBeginLine("/// ").Print(record.Name).Print(' ', pad).Print(" | ")
                    .Print(record.Size).PrintEndLine();
            }

            p.PrintBeginLine("/// ").PrintEndLine("</reference>");
            p.PrintEndLine();
        }
    }
}

#endif
