#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatVariantTypeExtensionsGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatVariantTypeExtensionsGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;

                p.PrintLine("partial interface IStatVariantTypeExtensions { }");
                p.PrintEndLine();

                p.PrintLine("partial struct StatVariantTypeExtended { }");
                p.PrintEndLine();

                p.PrintLine("static partial class StatVariantTypeExtensions");
                p.OpenScope();
                {
                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public static StatVariant ZeroVariant(this StatVariantType type)");
                    p.WithIncreasedIndent().PrintLine("=> new(type);");
                    p.PrintEndLine();

                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public static StatVariant OneVariant(this StatVariantType type)");
                    p.OpenScope();
                    {
                        p.PrintLine("return type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < active.Length; i++)
                            {
                                var record = active[i];

                                p.PrintBeginLine("StatVariantType.").Print(record.Name)
                                    .Print(" => new StatVariant(")
                                    .Print(record.One)
                                    .PrintEndLine("),");
                            }

                            p.PrintLine("_ => default,");
                        }
                        p.CloseScope("};");
                    }
                    p.CloseScope();
                    p.PrintEndLine();
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.COMMON_FOLDER)
            );

            context.AddCode("StatVariantTypeExtensions.gen.cs", p.Result);
        }
    }
}

#endif
