#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatSingleExtensionsGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatSingleExtensionsGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;

                p.PrintLine("public static partial class StatSingleValueExtensions");
                p.OpenScope();
                {
                    for (var i = 1; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public static StatSingle<").Print(record.Type)
                            .Print("> ToStatSingle(this ")
                            .PrintIf(record.Size > 8, "in ", "").Print(record.Type).PrintEndLine(" value)");
                        p.WithIncreasedIndent().PrintLine("=> new(value);");
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.COMMON_FOLDER)
            );

            context.AddCode("StatSingleExtensions.gen.cs", p.Result);
        }
    }
}

#endif
