<Project>
    <PropertyGroup>
        <BaseOutputPath>$(MSBuildThisFileDirectory)Build/$(MSBuildProjectName)/bin/</BaseOutputPath>
        <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)Build/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
        <ResultsDirectory>$(MSBuildThisFileDirectory)Build/$(MSBuildProjectName)/TestResults/</ResultsDirectory>
    </PropertyGroup>

    <Target Name="CopyBuildArtifacts" AfterTargets="Build"
            Condition="'$(Configuration)'=='Release' AND '$(MSBuildProjectName)'!='netstandard'
                AND '$(MSBuildProjectName)'!='System.Runtime.CompilerServices.Unsafe'">
        <ItemGroup>
            <DataFiles Include="$(OutDir)*.dll" Exclude="EncosyTower.LowLevel.Unsafe.dll" />
        </ItemGroup>
        <Copy SourceFiles="@(DataFiles)"
              DestinationFolder="$(MSBuildThisFileDirectory)../../Packages/com.laicasaane.encosy-tower/Plugins/$(AssemblyName)/"
              SkipUnchangedFiles="true" />
    </Target>
</Project>