/// <auto-generated>
///*******************************************************///
///                                                       ///
/// This file is auto-generated by StatTypeTableGenerator ///
///              DO NOT manually modify it!               ///
///                                                       ///
///*******************************************************///
/// </auto-generated>

using System;
using System.Collections.Generic;

namespace ApexionGame.SourceGen.Helpers.Entities.Stats
{
    public static class StatTypeTable
    {
        public const string NAMESPACE = "ApexionGame.Entities.Stats";
        public const string SKIP_ATTRIBUTE = $"global::{NAMESPACE}.SkipSourceGeneratorsForAssemblyAttribute";

        public static readonly Dictionary<string, string> EnumTypeMap = new(StringComparer.Ordinal) {
            { "sbyte", "SByte" },
            { "byte", "Byte" },
            { "short", "Short" },
            { "ushort", "UShort" },
            { "int", "Int" },
            { "uint", "UInt" },
            { "long", "Long" },
            { "ulong", "ULong" },
        };

        public static readonly string[] Types = new string[] {
            "None",
            "bool",
            "sbyte",
            "byte",
            "short",
            "ushort",
            "int",
            "uint",
            "long",
            "ulong",
            "half",
            "half2",
            "half3",
            "half4",
            "float",
            "float2",
            "float3",
            "float4",
            "double",
        };

        public static readonly string[] TypeNames = new string[] {
            "None",
            "Bool",
            "SByte",
            "Byte",
            "Short",
            "UShort",
            "Int",
            "UInt",
            "Long",
            "ULong",
            "Half",
            "Half2",
            "Half3",
            "Half4",
            "Float",
            "Float2",
            "Float3",
            "Float4",
            "Double",
        };

        public static readonly string[] Namespaces = new string[] {
            "AGES",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "UM",
            "UM",
            "UM",
            "UM",
            "",
            "UM",
            "UM",
            "UM",
            "",
        };

        public static readonly int[] Sizes = new int[] {
            1,  // None
            1,  // bool
            1,  // sbyte
            1,  // byte
            2,  // short
            2,  // ushort
            4,  // int
            4,  // uint
            8,  // long
            8,  // ulong
            2,  // half
            4,  // half2
            6,  // half3
            8,  // half4
            4,  // float
            8,  // float2
            12, // float3
            16, // float4
            8,  // double
        };
    }

    public enum StatVariantType : byte
    {
        /// <summary>
        /// <see cref="None"/> | 1 byte.
        /// </summary>
        None = 0,

        /// <summary>
        /// <see cref="bool"/> | 1 byte.
        /// </summary>
        Bool = 1,

        /// <summary>
        /// <see cref="sbyte"/> | 1 byte.
        /// </summary>
        SByte = 2,

        /// <summary>
        /// <see cref="byte"/> | 1 byte.
        /// </summary>
        Byte = 3,

        /// <summary>
        /// <see cref="short"/> | 2 bytes.
        /// </summary>
        Short = 4,

        /// <summary>
        /// <see cref="ushort"/> | 2 bytes.
        /// </summary>
        UShort = 5,

        /// <summary>
        /// <see cref="int"/> | 4 bytes.
        /// </summary>
        Int = 6,

        /// <summary>
        /// <see cref="uint"/> | 4 bytes.
        /// </summary>
        UInt = 7,

        /// <summary>
        /// <see cref="long"/> | 8 bytes.
        /// </summary>
        Long = 8,

        /// <summary>
        /// <see cref="ulong"/> | 8 bytes.
        /// </summary>
        ULong = 9,

        /// <summary>
        /// <see cref="half"/> | 2 bytes.
        /// </summary>
        Half = 10,

        /// <summary>
        /// <see cref="half2"/> | 4 bytes.
        /// </summary>
        Half2 = 11,

        /// <summary>
        /// <see cref="half3"/> | 6 bytes.
        /// </summary>
        Half3 = 12,

        /// <summary>
        /// <see cref="half4"/> | 8 bytes.
        /// </summary>
        Half4 = 13,

        /// <summary>
        /// <see cref="float"/> | 4 bytes.
        /// </summary>
        Float = 14,

        /// <summary>
        /// <see cref="float2"/> | 8 bytes.
        /// </summary>
        Float2 = 15,

        /// <summary>
        /// <see cref="float3"/> | 12 bytes.
        /// </summary>
        Float3 = 16,

        /// <summary>
        /// <see cref="float4"/> | 16 bytes.
        /// </summary>
        Float4 = 17,

        /// <summary>
        /// <see cref="double"/> | 8 bytes.
        /// </summary>
        Double = 18,

    }
}

