#if UNITY_MATHEMATICS

/// <auto-generated>
///***************************************************///
///                                                   ///
/// This file is auto-generated by ByteBoolsGenerator ///
///            DO NOT manually modify it!             ///
///                                                   ///
///***************************************************///
/// </auto-generated>

#pragma warning disable

namespace EncosyTower.Common
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;
    using Unity.Mathematics;

    /// <summary>
    /// A blittable variant of <see cref="bool2"/> whose components are <see cref="ByteBool"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool2 : IEquatable<ByteBool2>
    {
        public ByteBool x;
        public ByteBool y;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2(ByteBool x, ByteBool y)
        {
            this.x = x;
            this.y = y;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2(bool2 value)
        {
            this.x = value.x;
            this.y = value.y;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool2 other)
            => x == other.x && y == other.y;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool2 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(x, y);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool2)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool2 lhs, ByteBool2 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool2 lhs, ByteBool2 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool2(ByteBool2 value)
            => new(value.x, value.y);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool2(bool2 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool2x2"/> whose columns are <see cref="ByteBool2"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool2x2 : IEquatable<ByteBool2x2>
    {
        public ByteBool2 c0;
        public ByteBool2 c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x2(ByteBool2 c0, ByteBool2 c1)
        {
            this.c0 = c0;
            this.c1 = c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x2(bool2x2 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool2x2 other)
            => c0 == other.c0 && c1 == other.c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool2x2 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool2x2)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool2x2 lhs, ByteBool2x2 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool2x2 lhs, ByteBool2x2 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool2x2(ByteBool2x2 value)
            => new(value.c0, value.c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool2x2(bool2x2 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool2x3"/> whose columns are <see cref="ByteBool2"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool2x3 : IEquatable<ByteBool2x3>
    {
        public ByteBool2 c0;
        public ByteBool2 c1;
        public ByteBool2 c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x3(ByteBool2 c0, ByteBool2 c1, ByteBool2 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x3(bool2x3 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool2x3 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool2x3 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool2x3)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool2x3 lhs, ByteBool2x3 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool2x3 lhs, ByteBool2x3 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool2x3(ByteBool2x3 value)
            => new(value.c0, value.c1, value.c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool2x3(bool2x3 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool2x4"/> whose columns are <see cref="ByteBool2"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool2x4 : IEquatable<ByteBool2x4>
    {
        public ByteBool2 c0;
        public ByteBool2 c1;
        public ByteBool2 c2;
        public ByteBool2 c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x4(ByteBool2 c0, ByteBool2 c1, ByteBool2 c2, ByteBool2 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool2x4(bool2x4 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
            this.c3 = value.c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool2x4 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2 && c3 == other.c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool2x4 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2, c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool2x4)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool2x4 lhs, ByteBool2x4 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool2x4 lhs, ByteBool2x4 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool2x4(ByteBool2x4 value)
            => new(value.c0, value.c1, value.c2, value.c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool2x4(bool2x4 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool3"/> whose components are <see cref="ByteBool"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool3 : IEquatable<ByteBool3>
    {
        public ByteBool x;
        public ByteBool y;
        public ByteBool z;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3(ByteBool x, ByteBool y, ByteBool z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3(bool3 value)
        {
            this.x = value.x;
            this.y = value.y;
            this.z = value.z;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool3 other)
            => x == other.x && y == other.y && z == other.z;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool3 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(x, y, z);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool3)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool3 lhs, ByteBool3 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool3 lhs, ByteBool3 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool3(ByteBool3 value)
            => new(value.x, value.y, value.z);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool3(bool3 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool3x2"/> whose columns are <see cref="ByteBool3"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool3x2 : IEquatable<ByteBool3x2>
    {
        public ByteBool3 c0;
        public ByteBool3 c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x2(ByteBool3 c0, ByteBool3 c1)
        {
            this.c0 = c0;
            this.c1 = c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x2(bool3x2 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool3x2 other)
            => c0 == other.c0 && c1 == other.c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool3x2 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool3x2)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool3x2 lhs, ByteBool3x2 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool3x2 lhs, ByteBool3x2 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool3x2(ByteBool3x2 value)
            => new(value.c0, value.c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool3x2(bool3x2 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool3x3"/> whose columns are <see cref="ByteBool3"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool3x3 : IEquatable<ByteBool3x3>
    {
        public ByteBool3 c0;
        public ByteBool3 c1;
        public ByteBool3 c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x3(ByteBool3 c0, ByteBool3 c1, ByteBool3 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x3(in bool3x3 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool3x3 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool3x3 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool3x3)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(in ByteBool3x3 lhs, in ByteBool3x3 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(in ByteBool3x3 lhs, in ByteBool3x3 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool3x3(in ByteBool3x3 value)
            => new(value.c0, value.c1, value.c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool3x3(in bool3x3 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool3x4"/> whose columns are <see cref="ByteBool3"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool3x4 : IEquatable<ByteBool3x4>
    {
        public ByteBool3 c0;
        public ByteBool3 c1;
        public ByteBool3 c2;
        public ByteBool3 c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x4(ByteBool3 c0, ByteBool3 c1, ByteBool3 c2, ByteBool3 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool3x4(in bool3x4 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
            this.c3 = value.c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool3x4 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2 && c3 == other.c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool3x4 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2, c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool3x4)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(in ByteBool3x4 lhs, in ByteBool3x4 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(in ByteBool3x4 lhs, in ByteBool3x4 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool3x4(in ByteBool3x4 value)
            => new(value.c0, value.c1, value.c2, value.c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool3x4(in bool3x4 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool4"/> whose components are <see cref="ByteBool"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool4 : IEquatable<ByteBool4>
    {
        public ByteBool x;
        public ByteBool y;
        public ByteBool z;
        public ByteBool w;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4(ByteBool x, ByteBool y, ByteBool z, ByteBool w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4(bool4 value)
        {
            this.x = value.x;
            this.y = value.y;
            this.z = value.z;
            this.w = value.w;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool4 other)
            => x == other.x && y == other.y && z == other.z && w == other.w;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool4 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(x, y, z, w);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool4)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool4 lhs, ByteBool4 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool4 lhs, ByteBool4 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool4(ByteBool4 value)
            => new(value.x, value.y, value.z, value.w);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool4(bool4 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool4x2"/> whose columns are <see cref="ByteBool4"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool4x2 : IEquatable<ByteBool4x2>
    {
        public ByteBool4 c0;
        public ByteBool4 c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x2(ByteBool4 c0, ByteBool4 c1)
        {
            this.c0 = c0;
            this.c1 = c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x2(bool4x2 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool4x2 other)
            => c0 == other.c0 && c1 == other.c1;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool4x2 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool4x2)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(ByteBool4x2 lhs, ByteBool4x2 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(ByteBool4x2 lhs, ByteBool4x2 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool4x2(ByteBool4x2 value)
            => new(value.c0, value.c1);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool4x2(bool4x2 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool4x3"/> whose columns are <see cref="ByteBool4"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool4x3 : IEquatable<ByteBool4x3>
    {
        public ByteBool4 c0;
        public ByteBool4 c1;
        public ByteBool4 c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x3(ByteBool4 c0, ByteBool4 c1, ByteBool4 c2)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x3(in bool4x3 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool4x3 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool4x3 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool4x3)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(in ByteBool4x3 lhs, in ByteBool4x3 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(in ByteBool4x3 lhs, in ByteBool4x3 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool4x3(in ByteBool4x3 value)
            => new(value.c0, value.c1, value.c2);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool4x3(in bool4x3 value)
            => new(value);
    }

    /// <summary>
    /// A blittable variant of <see cref="bool4x4"/> whose columns are <see cref="ByteBool4"/>.
    /// </summary>
    [Serializable]
    public partial struct ByteBool4x4 : IEquatable<ByteBool4x4>
    {
        public ByteBool4 c0;
        public ByteBool4 c1;
        public ByteBool4 c2;
        public ByteBool4 c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x4(ByteBool4 c0, ByteBool4 c1, ByteBool4 c2, ByteBool4 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public ByteBool4x4(in bool4x4 value)
        {
            this.c0 = value.c0;
            this.c1 = value.c1;
            this.c2 = value.c2;
            this.c3 = value.c3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool Equals(ByteBool4x4 other)
            => c0 == other.c0 && c1 == other.c1 && c2 == other.c2 && c3 == other.c3;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
            => obj is ByteBool4x4 other && Equals(other);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override int GetHashCode()
            => HashValue.Combine(c0, c1, c2, c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override string ToString()
            => ((bool4x4)this).ToString();

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(in ByteBool4x4 lhs, in ByteBool4x4 rhs)
            => lhs.Equals(rhs);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(in ByteBool4x4 lhs, in ByteBool4x4 rhs)
            => lhs.Equals(rhs) == false;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator bool4x4(in ByteBool4x4 value)
            => new(value.c0, value.c1, value.c2, value.c3);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator ByteBool4x4(in bool4x4 value)
            => new(value);
    }

}

#if UNITY_COLLECTIONS

namespace EncosyTower.Common
{
    using System.Runtime.CompilerServices;
    using EncosyTower.Collections;
    using EncosyTower.Conversion;
    using Unity.Collections;

    partial struct ByteBool2 : IToFixedString, IToFixedString<FixedString64Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString64Bytes ToFixedString()
        {
            FixedString64Bytes fs = "bool2(";
            fs.Append(x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(y.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool2x2 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool2x2(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool2x3 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool2x3(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool2x4 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool2x4(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.y.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool3 : IToFixedString, IToFixedString<FixedString64Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString64Bytes ToFixedString()
        {
            FixedString64Bytes fs = "bool3(";
            fs.Append(x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(z.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool3x2 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool3x2(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool3x3 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool3x3(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.z.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool3x4 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool3x4(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.z.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool4 : IToFixedString, IToFixedString<FixedString64Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString64Bytes ToFixedString()
        {
            FixedString64Bytes fs = "bool4(";
            fs.Append(x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(w.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool4x2 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool4x2(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.w.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool4x3 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool4x3(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.w.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

    partial struct ByteBool4x4 : IToFixedString, IToFixedString<FixedString128Bytes>
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes fs = "bool4x4(";
            fs.Append(c0.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.x.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.y.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.z.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(' ');
            fs.Append(c0.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c1.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c2.w.ToFixedString());
            fs.Append(',');
            fs.Append(' ');
            fs.Append(c3.w.ToFixedString());
            fs.Append(')');
            return fs;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly TFixedString ToFixedString<TFixedString>()
            where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes
            => ToFixedString().CastTo<TFixedString>();
    }

}

#endif

#endif
