#if UNITY_EDITOR && ANNULUS_CODEGEN && ENCOSY_BYTE_BOOLS_GENERATOR

using System;
using System.Linq;
using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace EncosyTower.Editor.Common
{
    [Generator]
    [ApiForEditor]
    internal sealed class ByteBoolsGenerator : ICodeGenerator
    {
        private const string AGGRESSIVE_INLINING = "[MethodImpl(MethodImplOptions.AggressiveInlining)]";

        private static readonly string[] s_components = new string[] { "x", "y", "z", "w" };

        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintLine("#if UNITY_MATHEMATICS").PrintEndLine();
            p.PrintAutoGeneratedBlock(nameof(ByteBoolsGenerator));
            p.PrintEndLine();
            p.PrintLine("#pragma warning disable");
            p.PrintEndLine();

            p.PrintLine("namespace EncosyTower.Common");
            p.OpenScope();
            {
                p.PrintLine("using System;");
                p.PrintLine("using System.Runtime.CompilerServices;");
                p.PrintLine("using System.Runtime.InteropServices;");
                p.PrintLine("using Unity.Mathematics;");
                p.PrintEndLine();

                for (var rows = 2; rows <= 4; rows++)
                {
                    WriteVector(ref p, rows);

                    for (var columns = 2; columns <= 4; columns++)
                    {
                        WriteMatrix(ref p, rows, columns);
                    }
                }
            }
            p.CloseScope();
            p.PrintEndLine();

            p.Print("#if UNITY_COLLECTIONS").PrintEndLine();
            p.PrintEndLine();
            p.PrintLine("namespace EncosyTower.Common");
            p.OpenScope();
            {
                p.PrintLine("using System.Runtime.CompilerServices;");
                p.PrintLine("using EncosyTower.Collections;");
                p.PrintLine("using EncosyTower.Conversion;");
                p.PrintLine("using Unity.Collections;");
                p.PrintEndLine();

                for (var rows = 2; rows <= 4; rows++)
                {
                    WriteVectorToFixedString(ref p, rows);

                    for (var columns = 2; columns <= 4; columns++)
                    {
                        WriteMatrixToFixedString(ref p, rows, columns);
                    }
                }
            }
            p.CloseScope();
            p.PrintEndLine();
            p.Print("#endif").PrintEndLine();
            p.PrintEndLine();
            p.Print("#endif").PrintEndLine();

            context.OverrideFolderPath(CodeGenAPI.GetOutputFolderPathFromCaller());
            context.AddCode("ByteBools.gen.cs", p.Result);
        }

        private static void WriteVector(ref Printer p, int size)
        {
            var typeName = $"ByteBool{size}";
            var boolType = $"bool{size}";
            var components = s_components.AsSpan(0, size).ToArray();

            p.PrintLine("/// <summary>");
            p.PrintLine($"/// A blittable variant of <see cref=\"{boolType}\"/> whose components are <see cref=\"ByteBool\"/>.");
            p.PrintLine("/// </summary>");
            p.PrintLine("[Serializable]");
            p.PrintLine($"public partial struct {typeName} : IEquatable<{typeName}>");
            p.OpenScope();
            {
                foreach (var c in components)
                {
                    p.PrintLine($"public ByteBool {c};");
                }

                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public {typeName}({string.Join(", ", components.Select(static c => $"ByteBool {c}"))})");
                p.OpenScope();
                {
                    foreach (var c in components)
                    {
                        p.PrintLine($"this.{c} = {c};");
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public {typeName}({boolType} value)");
                p.OpenScope();
                {
                    foreach (var c in components)
                    {
                        p.PrintLine($"this.{c} = value.{c};");
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public readonly bool Equals({typeName} other)");
                p.WithIncreasedIndent().PrintLine($"=> {string.Join(" && ", components.Select(static c => $"{c} == other.{c}"))};");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override bool Equals(object obj)");
                p.WithIncreasedIndent().PrintLine($"=> obj is {typeName} other && Equals(other);");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override int GetHashCode()");
                p.WithIncreasedIndent().PrintLine($"=> HashValue.Combine({string.Join(", ", components)});");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override string ToString()");
                p.WithIncreasedIndent().PrintLine($"=> (({boolType})this).ToString();");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static bool operator ==({typeName} lhs, {typeName} rhs)");
                p.WithIncreasedIndent().PrintLine("=> lhs.Equals(rhs);");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static bool operator !=({typeName} lhs, {typeName} rhs)");
                p.WithIncreasedIndent().PrintLine("=> lhs.Equals(rhs) == false;");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static implicit operator {boolType}({typeName} value)");
                p.WithIncreasedIndent().PrintLine($"=> new({string.Join(", ", components.Select(static c => $"value.{c}"))});");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static implicit operator {typeName}({boolType} value)");
                p.WithIncreasedIndent().PrintLine("=> new(value);");
            }
            p.CloseScope();
            p.PrintEndLine();
        }

        private static void WriteMatrix(ref Printer p, int rows, int columns)
        {
            var typeName = $"ByteBool{rows}x{columns}";
            var boolType = $"bool{rows}x{columns}";
            var columnType = $"ByteBool{rows}";
            var inModifier = rows * columns > 8 ? "in " : "";
            var fields = Enumerable.Range(0, columns).Select(static i => $"c{i}").ToArray();

            p.PrintLine("/// <summary>");
            p.PrintLine($"/// A blittable variant of <see cref=\"{boolType}\"/> whose columns are <see cref=\"{columnType}\"/>.");
            p.PrintLine("/// </summary>");
            p.PrintLine("[Serializable]");
            p.PrintLine($"public partial struct {typeName} : IEquatable<{typeName}>");
            p.OpenScope();
            {
                foreach (var f in fields)
                {
                    p.PrintLine($"public {columnType} {f};");
                }

                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public {typeName}({string.Join(", ", fields.Select(f => $"{columnType} {f}"))})");
                p.OpenScope();
                {
                    foreach (var f in fields)
                    {
                        p.PrintLine($"this.{f} = {f};");
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public {typeName}({inModifier}{boolType} value)");
                p.OpenScope();
                {
                    foreach (var f in fields)
                    {
                        p.PrintLine($"this.{f} = value.{f};");
                    }
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public readonly bool Equals({typeName} other)");
                p.WithIncreasedIndent().PrintLine($"=> {string.Join(" && ", fields.Select(static f => $"{f} == other.{f}"))};");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override bool Equals(object obj)");
                p.WithIncreasedIndent().PrintLine($"=> obj is {typeName} other && Equals(other);");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override int GetHashCode()");
                p.WithIncreasedIndent().PrintLine($"=> HashValue.Combine({string.Join(", ", fields)});");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly override string ToString()");
                p.WithIncreasedIndent().PrintLine($"=> (({boolType})this).ToString();");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static bool operator ==({inModifier}{typeName} lhs, {inModifier}{typeName} rhs)");
                p.WithIncreasedIndent().PrintLine("=> lhs.Equals(rhs);");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static bool operator !=({inModifier}{typeName} lhs, {inModifier}{typeName} rhs)");
                p.WithIncreasedIndent().PrintLine("=> lhs.Equals(rhs) == false;");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static implicit operator {boolType}({inModifier}{typeName} value)");
                p.WithIncreasedIndent().PrintLine($"=> new({string.Join(", ", fields.Select(static f => $"value.{f}"))});");
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public static implicit operator {typeName}({inModifier}{boolType} value)");
                p.WithIncreasedIndent().PrintLine("=> new(value);");
            }
            p.CloseScope();
            p.PrintEndLine();
        }

        private static void WriteVectorToFixedString(ref Printer p, int size)
        {
            var typeName = $"ByteBool{size}";
            var boolType = $"bool{size}";
            var fsType = "FixedString64Bytes";
            var components = s_components.AsSpan(0, size).ToArray();

            p.PrintLine($"partial struct {typeName} : IToFixedString, IToFixedString<{fsType}>");
            p.OpenScope();
            {
                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public readonly {fsType} ToFixedString()");
                p.OpenScope();
                {
                    p.PrintLine($"{fsType} fs = \"{boolType}(\";");

                    for (var i = 0; i < components.Length; i++)
                    {
                        if (i > 0)
                        {
                            p.PrintLine("fs.Append(',');");
                            p.PrintLine("fs.Append(' ');");
                        }

                        p.PrintLine($"fs.Append({components[i]}.ToFixedString());");
                    }

                    p.PrintLine("fs.Append(')');");
                    p.PrintLine("return fs;");
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly TFixedString ToFixedString<TFixedString>()");
                p.WithIncreasedIndent().PrintLine("where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes");
                p.WithIncreasedIndent().PrintLine("=> ToFixedString().CastTo<TFixedString>();");
            }
            p.CloseScope();
            p.PrintEndLine();
        }

        private static void WriteMatrixToFixedString(ref Printer p, int rows, int columns)
        {
            var typeName = $"ByteBool{rows}x{columns}";
            var boolType = $"bool{rows}x{columns}";
            var fsType = "FixedString128Bytes";

            p.PrintLine($"partial struct {typeName} : IToFixedString, IToFixedString<{fsType}>");
            p.OpenScope();
            {
                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine($"public readonly {fsType} ToFixedString()");
                p.OpenScope();
                {
                    p.PrintLine($"{fsType} fs = \"{boolType}(\";");

                    for (var r = 0; r < rows; r++)
                    {
                        for (var c = 0; c < columns; c++)
                        {
                            if (r > 0 || c > 0)
                            {
                                p.PrintLine("fs.Append(',');");
                                p.PrintLine("fs.Append(' ');");
                            }

                            if (r > 0 && c == 0)
                            {
                                p.PrintLine("fs.Append(' ');");
                            }

                            p.PrintLine($"fs.Append(c{c}.{s_components[r]}.ToFixedString());");
                        }
                    }

                    p.PrintLine("fs.Append(')');");
                    p.PrintLine("return fs;");
                }
                p.CloseScope();
                p.PrintEndLine();

                p.PrintLine(AGGRESSIVE_INLINING);
                p.PrintLine("public readonly TFixedString ToFixedString<TFixedString>()");
                p.WithIncreasedIndent().PrintLine("where TFixedString : unmanaged, INativeList<byte>, IUTF8Bytes");
                p.WithIncreasedIndent().PrintLine("=> ToFixedString().CastTo<TFixedString>();");
            }
            p.CloseScope();
            p.PrintEndLine();
        }
    }
}

#endif
