/// <auto-generated>
///******************************************************///
///                                                      ///
/// This file is auto-generated by StatDataSizeGenerator ///
///              DO NOT manually modify it!              ///
///                                                      ///
///******************************************************///
/// </auto-generated>

/// <reference>
/// LIST OF SUPPORTED TYPES AND THEIR SIZE
/// TYPE   | SIZE (bytes)
/// ------ | ------------
/// None   | 1
/// Bool   | 1
/// SByte  | 1
/// Byte   | 1
/// Short  | 2
/// UShort | 2
/// Int    | 4
/// UInt   | 4
/// Long   | 8
/// ULong  | 8
/// Half   | 2
/// Half2  | 4
/// Half3  | 6
/// Half4  | 8
/// Float  | 4
/// Float2 | 8
/// Float3 | 12
/// Float4 | 16
/// Double | 8
/// </reference>

#pragma warning disable

namespace ApexionGame.Entities.Stats
{
    /// <summary>
    /// Represents a collection of supported data sizes, in bytes, to store stat variants.
    /// </summary>
    public enum StatDataSize : byte
    {
        /// <summary>
        /// 2 bytes.
        /// </summary>
        Size2 = 2,

        /// <summary>
        /// 4 bytes.
        /// </summary>
        Size4 = 4,

        /// <summary>
        /// 6 bytes.
        /// </summary>
        Size6 = 6,

        /// <summary>
        /// 8 bytes.
        /// </summary>
        Size8 = 8,

        /// <summary>
        /// 12 bytes.
        /// </summary>
        Size12 = 12,

        /// <summary>
        /// 16 bytes.
        /// </summary>
        Size16 = 16,

    }

    partial interface IStatDataSizeExtensions { }

    partial struct StatDataSizeExtended { }

    static partial class StatDataSizeExtensions
    {
        partial class DisplayNames { }

        partial class FixedDisplayNames { }

        partial class FixedNames { }

        partial class Names { }

        partial class UnderlyingValues { }

        partial class Values { }

    }

}

