/// <auto-generated>
///*********************************************************///
///                                                         ///
/// This file is auto-generated by StatVariantTypeGenerator ///
///               DO NOT manually modify it!                ///
///                                                         ///
///*********************************************************///
/// </auto-generated>

#pragma warning disable

using EncosyTower.EnumExtensions;
using Unity.Mathematics;

namespace ApexionGame.Entities.Stats
{
    /// <summary>
    /// Represents a collection of supported value types that can be used in this stat system.
    /// </summary>
    [EnumExtensions]
    public enum StatVariantType : byte
    {
        /// <summary>
        /// <see cref="None"/> | 1 byte.
        /// </summary>
        None = 0,

        /// <summary>
        /// <see cref="bool"/> | 1 byte.
        /// </summary>
        Bool = 1,

        /// <summary>
        /// <see cref="sbyte"/> | 1 byte.
        /// </summary>
        SByte = 2,

        /// <summary>
        /// <see cref="byte"/> | 1 byte.
        /// </summary>
        Byte = 3,

        /// <summary>
        /// <see cref="short"/> | 2 bytes.
        /// </summary>
        Short = 4,

        /// <summary>
        /// <see cref="ushort"/> | 2 bytes.
        /// </summary>
        UShort = 5,

        /// <summary>
        /// <see cref="int"/> | 4 bytes.
        /// </summary>
        Int = 6,

        /// <summary>
        /// <see cref="uint"/> | 4 bytes.
        /// </summary>
        UInt = 7,

        /// <summary>
        /// <see cref="long"/> | 8 bytes.
        /// </summary>
        Long = 8,

        /// <summary>
        /// <see cref="ulong"/> | 8 bytes.
        /// </summary>
        ULong = 9,

        /// <summary>
        /// <see cref="half"/> | 2 bytes.
        /// </summary>
        Half = 10,

        /// <summary>
        /// <see cref="half2"/> | 4 bytes.
        /// </summary>
        Half2 = 11,

        /// <summary>
        /// <see cref="half3"/> | 6 bytes.
        /// </summary>
        Half3 = 12,

        /// <summary>
        /// <see cref="half4"/> | 8 bytes.
        /// </summary>
        Half4 = 13,

        /// <summary>
        /// <see cref="float"/> | 4 bytes.
        /// </summary>
        Float = 14,

        /// <summary>
        /// <see cref="float2"/> | 8 bytes.
        /// </summary>
        Float2 = 15,

        /// <summary>
        /// <see cref="float3"/> | 12 bytes.
        /// </summary>
        Float3 = 16,

        /// <summary>
        /// <see cref="float4"/> | 16 bytes.
        /// </summary>
        Float4 = 17,

        /// <summary>
        /// <see cref="double"/> | 8 bytes.
        /// </summary>
        Double = 18,

    }

    partial interface IStatVariantTypeExtensions { }

    partial struct StatVariantTypeExtended { }

    static partial class StatVariantTypeExtensions
    {
        partial class DisplayNames { }

        partial class FixedDisplayNames { }

        partial class FixedNames { }

        partial class Names { }

        partial class UnderlyingValues { }

        partial class Values { }

    }

}

