/// <auto-generated>
///*******************************************************************///
///                                                                   ///
/// This file is auto-generated by StatVariantTypeExtensionsGenerator ///
///                    DO NOT manually modify it!                     ///
///                                                                   ///
///*******************************************************************///
/// </auto-generated>

#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;

namespace ApexionGame.Entities.Stats
{
    partial interface IStatVariantTypeExtensions { }

    partial struct StatVariantTypeExtended { }

    static partial class StatVariantTypeExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatVariant ZeroVariant(this StatVariantType type)
            => new(type);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatVariant OneVariant(this StatVariantType type)
        {
            return type switch
            {
                StatVariantType.None => new StatVariant(new None()),
                StatVariantType.Bool => new StatVariant(true),
                StatVariantType.SByte => new StatVariant((sbyte)1),
                StatVariantType.Byte => new StatVariant((byte)1),
                StatVariantType.Short => new StatVariant((short)1),
                StatVariantType.UShort => new StatVariant((ushort)1),
                StatVariantType.Int => new StatVariant((int)1),
                StatVariantType.UInt => new StatVariant((uint)1),
                StatVariantType.Long => new StatVariant((long)1),
                StatVariantType.ULong => new StatVariant((ulong)1),
                StatVariantType.Half => new StatVariant(math.half(1f)),
                StatVariantType.Half2 => new StatVariant(math.half2(1f)),
                StatVariantType.Half3 => new StatVariant(math.half3(1f)),
                StatVariantType.Half4 => new StatVariant(math.half4(1f)),
                StatVariantType.Float => new StatVariant((float)1f),
                StatVariantType.Float2 => new StatVariant(new float2(1f)),
                StatVariantType.Float3 => new StatVariant(new float3(1f)),
                StatVariantType.Float4 => new StatVariant(new float4(1f)),
                StatVariantType.Double => new StatVariant((double)1.0),
                _ => default,
            };
        }

    }

}

