#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using System;
using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatTypeTableGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatTypeTableGenerator));
            p.PrintEndLine();
            p.PrintLine(@"using System;
using System.Collections.Generic;
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.ROSLYN_NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;

                WriteTable(ref p, active);
                p.PrintEndLine();

                WriteEnum(ref p, active);
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.ROSLYN_HELPERS_FOLDER)
            );

            context.AddCode("StatTypeTable.gen.cs", p.Result);
        }

        private static void WriteTable(ref Printer p, TypeRecord[] active)
        {
            p.PrintLine("public static class StatTypeTable");
            p.OpenScope();
            {
                p.PrintBeginLine("public const string NAMESPACE = \"")
                    .Print(StatTypeTable.NAMESPACE).PrintEndLine("\";");

                p.PrintLine(
                    "public const string SKIP_ATTRIBUTE "
                    + "= $\"global::{NAMESPACE}.SkipSourceGeneratorsForAssemblyAttribute\";"
                );

                p.PrintEndLine();

                p.PrintLine("public static readonly Dictionary<string, string> EnumTypeMap "
                    + "= new(StringComparer.Ordinal) {");
                p = p.IncreasedIndent();
                {
                    var underlyingTypes = StatTypeTable.EnumUnderlyingTypes;

                    for (var i = 0; i < underlyingTypes.Length; i++)
                    {
                        var record = StatTypeTable.Find(underlyingTypes[i]);

                        p.PrintBeginLine("{ \"").Print(record.Type).Print("\", \"")
                            .Print(record.Name).PrintEndLine("\" },");
                    }
                }
                p = p.DecreasedIndent();
                p.PrintLine("};");
                p.PrintEndLine();

                WriteStringArray(ref p, "Types", active, static x => x.Type);
                p.PrintEndLine();

                WriteStringArray(ref p, "TypeNames", active, static x => x.Name);
                p.PrintEndLine();

                WriteStringArray(ref p, "Namespaces", active, static x => x.Ns);
                p.PrintEndLine();

                p.PrintLine("public static readonly int[] Sizes = new int[] {");
                p = p.IncreasedIndent();
                {
                    var padding = MaxSizeTextLength(active);

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];
                        var text = record.Size.ToString();

                        p.PrintBeginLine().Print(text).Print(',')
                            .Print(' ', padding - text.Length + 1)
                            .Print("// ").PrintEndLine(record.Type);
                    }
                }
                p = p.DecreasedIndent();
                p.PrintLine("};");
            }
            p.CloseScope();
        }

        private static void WriteStringArray(
              ref Printer p
            , string fieldName
            , TypeRecord[] active
            , Func<TypeRecord, string> selector
        )
        {
            p.PrintBeginLine("public static readonly string[] ").Print(fieldName)
                .PrintEndLine(" = new string[] {");

            p = p.IncreasedIndent();
            {
                for (var i = 0; i < active.Length; i++)
                {
                    p.PrintBeginLine("\"").Print(selector(active[i])).PrintEndLine("\",");
                }
            }
            p = p.DecreasedIndent();
            p.PrintLine("};");
        }

        private static void WriteEnum(ref Printer p, TypeRecord[] active)
        {
            p.PrintLine("public enum StatVariantType : byte");
            p.OpenScope();
            {
                for (var i = 0; i < active.Length; i++)
                {
                    var record = active[i];

                    p.PrintLine("/// <summary>");
                    p.PrintBeginLine("/// <see cref=\"").Print(record.Type).Print("\"/> | ").Print(record.Size)
                        .PrintEndLineIf(record.Size > 1, " bytes.", " byte.");
                    p.PrintLine("/// </summary>");
                    p.PrintBeginLine(record.Name).Print(" = ").Print(i).PrintEndLine(",");
                    p.PrintEndLine();
                }
            }
            p.CloseScope();
        }

        private static int MaxSizeTextLength(TypeRecord[] active)
        {
            var max = 0;

            for (var i = 0; i < active.Length; i++)
            {
                var length = active[i].Size.ToString().Length;

                if (length > max)
                {
                    max = length;
                }
            }

            return max;
        }
    }
}

#endif
