#if UNITY_EDITOR && ANNULUS_CODEGEN && APEXION_STAT_VALUE_TYPES_GENERATOR

using EncosyTower.CodeGen;
using EncosyTower.Core;
using UnityCodeGen;

namespace ApexionGame.Entities.Stats.Generators
{
    [Generator]
    [ApiForEditor]
    internal sealed class StatVariantGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var p = Printer.DefaultLarge;
            p.PrintAutoGeneratedBlock(nameof(StatVariantGenerator));
            p.PrintEndLine();
            p.PrintLine(@"#pragma warning disable

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using EncosyTower.Common;
using Unity.Mathematics;
");

            p.PrintBeginLine("namespace ").PrintEndLine(StatTypeTable.NAMESPACE);
            p.OpenScope();
            {
                var active = StatTypeTable.Active;

                p.PrintLine(StatTypeTable.STRUCT_LAYOUT_EXPLICIT);
                p.PrintLine("partial struct StatVariant : IEquatable<StatVariant>");
                p.OpenScope();
                {
                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintBeginLine(StatTypeTable.FIELD_OFFSET_0)
                            .Print(" public ").Print(record.Type)
                            .Print(" ").Print(record.Name).PrintEndLine(";");
                    }

                    var typeFieldOffset = string.Format(
                          StatTypeTable.FIELD_OFFSET_FORMAT
                        , StatTypeTable.MaxTypeSize
                    );

                    p.PrintBeginLine(typeFieldOffset).PrintEndLine(" public StatVariantType Type;");
                    p.PrintEndLine();

                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public StatVariant(StatVariantType type) : this()");
                    p.OpenScope();
                    {
                        p.PrintLine("Type = type;");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public StatVariant(")
                            .PrintIf(record.Size > 8, "in ", "").Print(record.Type).PrintEndLine(" value) : this()");
                        p.OpenScope();
                        {
                            p.PrintBeginLine("Type = StatVariantType.").Print(record.Name).PrintEndLine(";");
                            p.PrintBeginLine(record.Name).PrintEndLine(" = value;");
                        }
                        p.CloseScope();
                        p.PrintEndLine();
                    }

                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public static bool operator ==(in StatVariant a, in StatVariant b)");
                    p.OpenScope();
                    {
                        p.PrintLine("return a.Equals(b);");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public static bool operator !=(in StatVariant a, in StatVariant b)");
                    p.OpenScope();
                    {
                        p.PrintLine("return a.Equals(b) == false;");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine("public readonly bool Equals(StatVariant other)");
                    p.OpenScope();
                    {
                        p.PrintLine("if (Type != other.Type) return false;");
                        p.PrintEndLine();

                        p.PrintLine("return Type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < active.Length; i++)
                            {
                                var record = active[i];

                                p.PrintBeginLine("StatVariantType.").Print(record.Name)
                                    .Print(" => ").Print(record.Name);

                                if (record.Eq)
                                {
                                    p.Print(" == other.").Print(record.Name).PrintEndLine(",");
                                }
                                else
                                {
                                    p.Print(".Equals(other.").Print(record.Name).PrintEndLine("),");
                                }
                            }

                            p.PrintLine("_ => false,");
                        }
                        p.CloseScope("};");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                    p.PrintLine("public readonly override bool Equals(object obj)");
                    p.OpenScope();
                    {
                        p.PrintLine("return obj is StatVariant other && Equals(other);");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine("public readonly override int GetHashCode()");
                    p.OpenScope();
                    {
                        p.PrintLine("return Type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < active.Length; i++)
                            {
                                var record = active[i];

                                p.PrintBeginLine("StatVariantType.").Print(record.Name)
                                    .Print(" => HashValue.Combine(Type, ")
                                    .Print(record.Name).PrintEndLine("),");
                            }

                            p.PrintLine("_ => 0,");
                        }
                        p.CloseScope("};");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine("public readonly bool TrySetValueTo(ref StatVariant destination)");
                    p.OpenScope();
                    {
                        p.PrintLine("if (Type != destination.Type)");
                        p.OpenScope();
                        {
                            p.PrintLine("return false;");
                        }
                        p.CloseScope();
                        p.PrintEndLine();

                        p.PrintLine("Option<StatVariant> valueOpt = Type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < active.Length; i++)
                            {
                                var record = active[i];

                                p.PrintBeginLine("StatVariantType.").Print(record.Name)
                                    .Print(" => Option.Some<StatVariant>(")
                                    .Print(record.Name)
                                    .PrintEndLine("),");
                            }

                            p.PrintLine("_ => Option.None,");
                        }
                        p.CloseScope("};");
                        p.PrintEndLine();

                        p.PrintLine("destination = valueOpt.GetValueOrDefault();");
                        p.PrintLine("return valueOpt.HasValue;");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    p.PrintLine("public readonly void SetValueTo(ref StatVariant destination)");
                    p.OpenScope();
                    {
                        p.PrintLine("ThrowHelper.ThrowIfDestinationTypeMismatch(Type, destination.Type);");
                        p.PrintLine("ThrowHelper.ThrowIfUnsupportedType(destination.Type);");
                        p.PrintEndLine();

                        p.PrintLine("Option<StatVariant> valueOpt = Type switch");
                        p.OpenScope();
                        {
                            for (var i = 0; i < active.Length; i++)
                            {
                                var record = active[i];

                                p.PrintBeginLine("StatVariantType.").Print(record.Name)
                                    .Print(" => Option.Some<StatVariant>(")
                                    .Print(record.Name)
                                    .PrintEndLine("),");
                            }

                            p.PrintLine("_ => Option.None,");
                        }
                        p.CloseScope("};");
                        p.PrintEndLine();

                        p.PrintLine("destination = valueOpt.GetValueOrDefault();");
                    }
                    p.CloseScope();
                    p.PrintEndLine();

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public readonly bool TrySetValueTo(ref ")
                            .Print(record.Type).PrintEndLine(" destination)");
                        p.OpenScope();
                        {
                            p.PrintBeginLine("if (Type == StatVariantType.").Print(record.Name).PrintEndLine(")");
                            p.OpenScope();
                            {
                                p.PrintBeginLine("destination = ").Print(record.Name).PrintEndLine(";");
                                p.PrintLine("return true;");
                            }
                            p.CloseScope();
                            p.PrintEndLine();

                            p.PrintLine("return false;");
                        }
                        p.CloseScope();
                        p.PrintEndLine();
                    }

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public readonly void SetValueTo(ref ")
                            .Print(record.Type).PrintEndLine(" destination)");
                        p.OpenScope();
                        {
                            p.PrintBeginLine("ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.")
                                .Print(record.Name).PrintEndLine(");");
                            p.PrintLine("ThrowHelper.ThrowIfUnsupportedType(Type);");
                            p.PrintEndLine();

                            p.PrintBeginLine("destination = ").Print(record.Name).PrintEndLine(";");
                        }
                        p.CloseScope();
                        p.PrintEndLine();
                    }

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public static implicit operator StatVariant(")
                            .PrintIf(record.Size > 8, "in ", "").Print(record.Type).PrintEndLine(" value)");
                        p = p.IncreasedIndent();
                        {
                            p.PrintLine("=> new(value);");
                        }
                        p = p.DecreasedIndent();
                        p.PrintEndLine();
                    }

                    for (var i = 0; i < active.Length; i++)
                    {
                        var record = active[i];

                        p.PrintLine(StatTypeTable.AGGRESSIVE_INLINING);
                        p.PrintBeginLine("public static explicit operator ").Print(record.Type)
                            .PrintEndLine("(in StatVariant value)");
                        p.OpenScope();
                        {
                            p.PrintBeginLine(
                                    "ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType."
                                )
                                .Print(record.Name).PrintEndLine(");");

                            p.PrintLine("ThrowHelper.ThrowIfUnsupportedType(value.Type);");
                            p.PrintEndLine();

                            p.PrintBeginLine("return value.").Print(record.Name).PrintEndLine(";");
                        }
                        p.CloseScope();
                        p.PrintEndLine();
                    }
                }
                p.CloseScope();
                p.PrintEndLine();
            }
            p.CloseScope();
            p.PrintEndLine();

            context.OverrideFolderPath(
                CodeGenAPI.GetOutputFolderPathFromCaller(pathCombine: StatTypeTable.COMMON_FOLDER)
            );

            context.AddCode("StatVariant.gen.cs", p.Result);
        }
    }
}

#endif
