/// <auto-generated>
///*****************************************************///
///                                                     ///
/// This file is auto-generated by StatVariantGenerator ///
///             DO NOT manually modify it!              ///
///                                                     ///
///*****************************************************///
/// </auto-generated>

#pragma warning disable

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using EncosyTower.Common;
using Unity.Mathematics;

namespace ApexionGame.Entities.Stats
{
    [StructLayout(LayoutKind.Explicit)]
    partial struct StatVariant : IEquatable<StatVariant>
    {
        [FieldOffset(0)] public None None;
        [FieldOffset(0)] public bool Bool;
        [FieldOffset(0)] public sbyte SByte;
        [FieldOffset(0)] public byte Byte;
        [FieldOffset(0)] public short Short;
        [FieldOffset(0)] public ushort UShort;
        [FieldOffset(0)] public int Int;
        [FieldOffset(0)] public uint UInt;
        [FieldOffset(0)] public long Long;
        [FieldOffset(0)] public ulong ULong;
        [FieldOffset(0)] public half Half;
        [FieldOffset(0)] public half2 Half2;
        [FieldOffset(0)] public half3 Half3;
        [FieldOffset(0)] public half4 Half4;
        [FieldOffset(0)] public float Float;
        [FieldOffset(0)] public float2 Float2;
        [FieldOffset(0)] public float3 Float3;
        [FieldOffset(0)] public float4 Float4;
        [FieldOffset(0)] public double Double;
        [FieldOffset(16)] public StatVariantType Type;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(StatVariantType type) : this()
        {
            Type = type;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(None value) : this()
        {
            Type = StatVariantType.None;
            None = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(bool value) : this()
        {
            Type = StatVariantType.Bool;
            Bool = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(sbyte value) : this()
        {
            Type = StatVariantType.SByte;
            SByte = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(byte value) : this()
        {
            Type = StatVariantType.Byte;
            Byte = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(short value) : this()
        {
            Type = StatVariantType.Short;
            Short = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(ushort value) : this()
        {
            Type = StatVariantType.UShort;
            UShort = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(int value) : this()
        {
            Type = StatVariantType.Int;
            Int = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(uint value) : this()
        {
            Type = StatVariantType.UInt;
            UInt = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(long value) : this()
        {
            Type = StatVariantType.Long;
            Long = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(ulong value) : this()
        {
            Type = StatVariantType.ULong;
            ULong = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(half value) : this()
        {
            Type = StatVariantType.Half;
            Half = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(half2 value) : this()
        {
            Type = StatVariantType.Half2;
            Half2 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(half3 value) : this()
        {
            Type = StatVariantType.Half3;
            Half3 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(half4 value) : this()
        {
            Type = StatVariantType.Half4;
            Half4 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(float value) : this()
        {
            Type = StatVariantType.Float;
            Float = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(float2 value) : this()
        {
            Type = StatVariantType.Float2;
            Float2 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(in float3 value) : this()
        {
            Type = StatVariantType.Float3;
            Float3 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(in float4 value) : this()
        {
            Type = StatVariantType.Float4;
            Float4 = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public StatVariant(double value) : this()
        {
            Type = StatVariantType.Double;
            Double = value;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator ==(in StatVariant a, in StatVariant b)
        {
            return a.Equals(b);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool operator !=(in StatVariant a, in StatVariant b)
        {
            return a.Equals(b) == false;
        }

        public readonly bool Equals(StatVariant other)
        {
            if (Type != other.Type) return false;

            return Type switch
            {
                StatVariantType.None => None.Equals(other.None),
                StatVariantType.Bool => Bool == other.Bool,
                StatVariantType.SByte => SByte == other.SByte,
                StatVariantType.Byte => Byte == other.Byte,
                StatVariantType.Short => Short == other.Short,
                StatVariantType.UShort => UShort == other.UShort,
                StatVariantType.Int => Int == other.Int,
                StatVariantType.UInt => UInt == other.UInt,
                StatVariantType.Long => Long == other.Long,
                StatVariantType.ULong => ULong == other.ULong,
                StatVariantType.Half => Half == other.Half,
                StatVariantType.Half2 => Half2.Equals(other.Half2),
                StatVariantType.Half3 => Half3.Equals(other.Half3),
                StatVariantType.Half4 => Half4.Equals(other.Half4),
                StatVariantType.Float => Float == other.Float,
                StatVariantType.Float2 => Float2.Equals(other.Float2),
                StatVariantType.Float3 => Float3.Equals(other.Float3),
                StatVariantType.Float4 => Float4.Equals(other.Float4),
                StatVariantType.Double => Double == other.Double,
                _ => false,
            };
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly override bool Equals(object obj)
        {
            return obj is StatVariant other && Equals(other);
        }

        public readonly override int GetHashCode()
        {
            return Type switch
            {
                StatVariantType.None => HashValue.Combine(Type, None),
                StatVariantType.Bool => HashValue.Combine(Type, Bool),
                StatVariantType.SByte => HashValue.Combine(Type, SByte),
                StatVariantType.Byte => HashValue.Combine(Type, Byte),
                StatVariantType.Short => HashValue.Combine(Type, Short),
                StatVariantType.UShort => HashValue.Combine(Type, UShort),
                StatVariantType.Int => HashValue.Combine(Type, Int),
                StatVariantType.UInt => HashValue.Combine(Type, UInt),
                StatVariantType.Long => HashValue.Combine(Type, Long),
                StatVariantType.ULong => HashValue.Combine(Type, ULong),
                StatVariantType.Half => HashValue.Combine(Type, Half),
                StatVariantType.Half2 => HashValue.Combine(Type, Half2),
                StatVariantType.Half3 => HashValue.Combine(Type, Half3),
                StatVariantType.Half4 => HashValue.Combine(Type, Half4),
                StatVariantType.Float => HashValue.Combine(Type, Float),
                StatVariantType.Float2 => HashValue.Combine(Type, Float2),
                StatVariantType.Float3 => HashValue.Combine(Type, Float3),
                StatVariantType.Float4 => HashValue.Combine(Type, Float4),
                StatVariantType.Double => HashValue.Combine(Type, Double),
                _ => 0,
            };
        }

        public readonly bool TrySetValueTo(ref StatVariant destination)
        {
            if (Type != destination.Type)
            {
                return false;
            }

            Option<StatVariant> valueOpt = Type switch
            {
                StatVariantType.None => Option.Some<StatVariant>(None),
                StatVariantType.Bool => Option.Some<StatVariant>(Bool),
                StatVariantType.SByte => Option.Some<StatVariant>(SByte),
                StatVariantType.Byte => Option.Some<StatVariant>(Byte),
                StatVariantType.Short => Option.Some<StatVariant>(Short),
                StatVariantType.UShort => Option.Some<StatVariant>(UShort),
                StatVariantType.Int => Option.Some<StatVariant>(Int),
                StatVariantType.UInt => Option.Some<StatVariant>(UInt),
                StatVariantType.Long => Option.Some<StatVariant>(Long),
                StatVariantType.ULong => Option.Some<StatVariant>(ULong),
                StatVariantType.Half => Option.Some<StatVariant>(Half),
                StatVariantType.Half2 => Option.Some<StatVariant>(Half2),
                StatVariantType.Half3 => Option.Some<StatVariant>(Half3),
                StatVariantType.Half4 => Option.Some<StatVariant>(Half4),
                StatVariantType.Float => Option.Some<StatVariant>(Float),
                StatVariantType.Float2 => Option.Some<StatVariant>(Float2),
                StatVariantType.Float3 => Option.Some<StatVariant>(Float3),
                StatVariantType.Float4 => Option.Some<StatVariant>(Float4),
                StatVariantType.Double => Option.Some<StatVariant>(Double),
                _ => Option.None,
            };

            destination = valueOpt.GetValueOrDefault();
            return valueOpt.HasValue;
        }

        public readonly void SetValueTo(ref StatVariant destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, destination.Type);
            ThrowHelper.ThrowIfUnsupportedType(destination.Type);

            Option<StatVariant> valueOpt = Type switch
            {
                StatVariantType.None => Option.Some<StatVariant>(None),
                StatVariantType.Bool => Option.Some<StatVariant>(Bool),
                StatVariantType.SByte => Option.Some<StatVariant>(SByte),
                StatVariantType.Byte => Option.Some<StatVariant>(Byte),
                StatVariantType.Short => Option.Some<StatVariant>(Short),
                StatVariantType.UShort => Option.Some<StatVariant>(UShort),
                StatVariantType.Int => Option.Some<StatVariant>(Int),
                StatVariantType.UInt => Option.Some<StatVariant>(UInt),
                StatVariantType.Long => Option.Some<StatVariant>(Long),
                StatVariantType.ULong => Option.Some<StatVariant>(ULong),
                StatVariantType.Half => Option.Some<StatVariant>(Half),
                StatVariantType.Half2 => Option.Some<StatVariant>(Half2),
                StatVariantType.Half3 => Option.Some<StatVariant>(Half3),
                StatVariantType.Half4 => Option.Some<StatVariant>(Half4),
                StatVariantType.Float => Option.Some<StatVariant>(Float),
                StatVariantType.Float2 => Option.Some<StatVariant>(Float2),
                StatVariantType.Float3 => Option.Some<StatVariant>(Float3),
                StatVariantType.Float4 => Option.Some<StatVariant>(Float4),
                StatVariantType.Double => Option.Some<StatVariant>(Double),
                _ => Option.None,
            };

            destination = valueOpt.GetValueOrDefault();
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref None destination)
        {
            if (Type == StatVariantType.None)
            {
                destination = None;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref bool destination)
        {
            if (Type == StatVariantType.Bool)
            {
                destination = Bool;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref sbyte destination)
        {
            if (Type == StatVariantType.SByte)
            {
                destination = SByte;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref byte destination)
        {
            if (Type == StatVariantType.Byte)
            {
                destination = Byte;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref short destination)
        {
            if (Type == StatVariantType.Short)
            {
                destination = Short;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref ushort destination)
        {
            if (Type == StatVariantType.UShort)
            {
                destination = UShort;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref int destination)
        {
            if (Type == StatVariantType.Int)
            {
                destination = Int;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref uint destination)
        {
            if (Type == StatVariantType.UInt)
            {
                destination = UInt;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref long destination)
        {
            if (Type == StatVariantType.Long)
            {
                destination = Long;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref ulong destination)
        {
            if (Type == StatVariantType.ULong)
            {
                destination = ULong;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref half destination)
        {
            if (Type == StatVariantType.Half)
            {
                destination = Half;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref half2 destination)
        {
            if (Type == StatVariantType.Half2)
            {
                destination = Half2;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref half3 destination)
        {
            if (Type == StatVariantType.Half3)
            {
                destination = Half3;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref half4 destination)
        {
            if (Type == StatVariantType.Half4)
            {
                destination = Half4;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref float destination)
        {
            if (Type == StatVariantType.Float)
            {
                destination = Float;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref float2 destination)
        {
            if (Type == StatVariantType.Float2)
            {
                destination = Float2;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref float3 destination)
        {
            if (Type == StatVariantType.Float3)
            {
                destination = Float3;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref float4 destination)
        {
            if (Type == StatVariantType.Float4)
            {
                destination = Float4;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly bool TrySetValueTo(ref double destination)
        {
            if (Type == StatVariantType.Double)
            {
                destination = Double;
                return true;
            }

            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref None destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.None);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = None;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref bool destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Bool);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Bool;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref sbyte destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.SByte);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = SByte;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref byte destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Byte);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Byte;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref short destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Short);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Short;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref ushort destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.UShort);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = UShort;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref int destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Int);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Int;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref uint destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.UInt);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = UInt;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref long destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Long);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Long;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref ulong destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.ULong);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = ULong;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref half destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Half);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Half;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref half2 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Half2);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Half2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref half3 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Half3);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Half3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref half4 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Half4);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Half4;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref float destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Float);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Float;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref float2 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Float2);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Float2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref float3 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Float3);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Float3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref float4 destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Float4);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Float4;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public readonly void SetValueTo(ref double destination)
        {
            ThrowHelper.ThrowIfDestinationTypeMismatch(Type, StatVariantType.Double);
            ThrowHelper.ThrowIfUnsupportedType(Type);

            destination = Double;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(None value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(bool value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(sbyte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(byte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(short value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(ushort value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(int value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(uint value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(long value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(ulong value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(half value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(half2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(half3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(half4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(float value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(float2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(in float3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(in float4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator StatVariant(double value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator None(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.None);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.None;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator bool(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Bool);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Bool;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator sbyte(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.SByte);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.SByte;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator byte(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Byte);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Byte;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator short(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Short);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Short;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator ushort(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.UShort);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.UShort;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator int(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Int);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Int;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator uint(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.UInt);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.UInt;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator long(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Long);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Long;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator ulong(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.ULong);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.ULong;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator half(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Half);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Half;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator half2(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Half2);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Half2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator half3(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Half3);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Half3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator half4(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Half4);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Half4;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator float(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Float);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Float;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator float2(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Float2);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Float2;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator float3(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Float3);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Float3;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator float4(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Float4);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Float4;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator double(in StatVariant value)
        {
            ThrowHelper.ThrowIfExplicitlyConvertToWrongType(value.Type, StatVariantType.Double);
            ThrowHelper.ThrowIfUnsupportedType(value.Type);

            return value.Double;
        }

    }

}

