/// <auto-generated>
///**************************************************************///
///                                                              ///
/// This file is auto-generated by StatSingleExtensionsGenerator ///
///                  DO NOT manually modify it!                  ///
///                                                              ///
///**************************************************************///
/// </auto-generated>

#pragma warning disable

using System.Runtime.CompilerServices;
using Unity.Mathematics;

namespace ApexionGame.Entities.Stats
{
    public static partial class StatSingleValueExtensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<bool> ToStatSingle(this bool value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<sbyte> ToStatSingle(this sbyte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<byte> ToStatSingle(this byte value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<short> ToStatSingle(this short value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<ushort> ToStatSingle(this ushort value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<int> ToStatSingle(this int value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<uint> ToStatSingle(this uint value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<long> ToStatSingle(this long value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<ulong> ToStatSingle(this ulong value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half> ToStatSingle(this half value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half2> ToStatSingle(this half2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half3> ToStatSingle(this half3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<half4> ToStatSingle(this half4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float> ToStatSingle(this float value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float2> ToStatSingle(this float2 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float3> ToStatSingle(this in float3 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<float4> ToStatSingle(this in float4 value)
            => new(value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatSingle<double> ToStatSingle(this double value)
            => new(value);

    }

}

